import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VJC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{ position: "absolute", marginLeft: "100px", color: "green" }}
        >
          <p>Welcome to Viet's training nextjs lession</p>
          <Link href="/Screen/Home" style={{color: "blue"}}>Back to VJC</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
